apiVersion: apps/v1
kind: Deployment
metadata:
  name: rights-app-website-deployment
spec:
  template:
    spec:
      containers:
        - name: rights-app-website
          # required to use local image
          imagePullPolicy: Never
